### ISSUE TITLE
Interview Preparation

### ISSUE THREAD

**Issue by OSP123** [OSP123/post-grad-curriculum#10]
- Considering a vast majority of recent graduates are going to be on the job hunt, it makes sense to prepare these students for interviewing.

**Comment by OSP123** [comment]
@DaC00P mentioned https://github.com/jwasham/coding-interview-university as a source for coding interview prep and becoming a software engineer. The resource is pretty robust, so we could use it to determine what resources to take from it to just use for interviewing and/or creating lessons from.

**Comment by jaysonjphillips** [comment]
From a talk I gave last year at AfroTech: https://www.slideshare.net/jaysonjphillips/hack-it-til-you-make-it-acing-the-technical-interview

**Comment by OSP123** [comment]
The slideshow is great, but the picture of Kevin Hart under Big O Notation is better. We can definitely incorporate slides like this for visual learners (most students tend to fall into this category, it seems).
