### ISSUE TITLE
Structuring the Curriculum

### ISSUE THREAD

**Issue by OSP123** [OSP123/post-grad-curriculum#2]
### Possible solution: Structure curriculum similar to existing curriculum. 
  - If using existing curriculum, students have a structure they're used to following. 
  - Downside is that we would need to adapt curriculum towards online-only learning. Ie, replacing lectures with video lectures or slideshows. 
    - Videos can be uploaded to YouTube pretty easily.

**Comment by jaysonjphillips** [comment]
Would also suggest we look into a more modular/mix-and-match approach here too. 
eg - post-graduation, I would like to really study more CS fundamentals, so I can generate a package that pulls in CS, basic networking, algorithms, concurrency, etc in a continuing-ed course.

**Comment by Multishifties** [comment]
Reposting from slack : 

 I like this idea, but maybe we can combine the two? A ‘level 1’ folder ‘level 2’ folder which requires you to first do level 1 and so on. That way students can still do the individual lessons within the levels in any order they want?

Omar Patel [3 hours ago] 
Ooh, that’s a good idea

Omar Patel [3 hours ago] 
So, if they already completed the first levels, they can still go to the next. Also, it allows instructors to start adding material for stuff that’s waaaay later on ahead of time. I like it.

**Comment by Multishifties** [comment]
I would recommend every section we develop contain, at the minimum, the following information at the top in an easily accessible fashion. (although not necessarily in this order):

1. Prerequisites for this module.
2. Estimated time to complete this module.
3. Table of contents for this module.
4. Summary/Overview of module.
5. Author notes for this module.
6. Links to external resources.

**Comment by OSP123** [comment]
@jaysonjphillips  Excellent, let's try the mix and match approach and see how that works out. We can build this in a pretty agile way, since we can get immediate feedback from students as soon as anything is published. 

@Multishifties Great idea, I'll try that structure out for each module. Let's create a Readme for the structure of modules to start off with. Do you mind creating a template for how this structure should look like?

**Comment by OSP123** [comment]
Current structure will use mix/match approach, with levels indicating the order of topics. Topics could then contain subtopics that are standalone and can be mixed/matched with other subtopics. Each module will have something like what @Multishifties mentioned:

> 1. Prerequisites for this module.
> 2. Estimated time to complete this module.
> 3. Table of contents for this module.
> 4. Summary/Overview of module.
> 5. Author notes for this module.
> 6. Links to external resources.
